### ISSUE TITLE
Document comparing different computer vision libraries in a drone or a device

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Economics#5]

**Comment by tapaswenipathak** [comment]
https://paper.dropbox.com/doc/Document-comparing-different-computer-vision-libraries--AgaU_ZBNjAvE3y3QkRu5arCQAQ-OA5puDAhtWmBglYfkp9so

**Comment by NiharikaMessi** [comment]
@tapaswenipathak This work seems intresting,and it is my field , can I get access to this document ?

**Comment by Aashi15bansal** [comment]
@tapaswenipathak @KevinChittilapilly  : https://paper.dropbox.com/doc/Computer-Vision-libraries--Ag5niLGCNPQO9ogApSlwhj00Ag-w6CDfghuxzHiiMmomEogv

**Comment by tapaswenipathak** [comment]
cc @NiharikaMessi as well.
